/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import com.toedter.calendar.JDateChooser;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPasswordField;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

/**
 *
 * @author LUNA
 */
public class vistaPanelRegistro extends javax.swing.JPanel {

    /**
     * Creates new form vistaPanelRegistro
     */
    public vistaPanelRegistro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel3 = new javax.swing.JLabel();
        textNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textCorreo = new javax.swing.JTextField();
        textContrasena = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jDateNacimiento = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        radbtnCliente = new javax.swing.JRadioButton();
        radbtnAdmin = new javax.swing.JRadioButton();
        btnCancelar = new javax.swing.JButton();
        btnRegistrarse = new javax.swing.JButton();
        btnExaminar = new javax.swing.JButton();
        lblFoto = new javax.swing.JLabel();
        lblpassseguro = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText(" NetTube");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, 58));

        textNombre.setBackground(new java.awt.Color(63, 25, 56));
        textNombre.setForeground(new java.awt.Color(255, 255, 255));
        add(textNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 189, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("NOMBRE");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CORREO");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, 30));

        textCorreo.setBackground(new java.awt.Color(63, 25, 56));
        textCorreo.setForeground(new java.awt.Color(255, 255, 255));
        add(textCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 189, -1));

        textContrasena.setBackground(new java.awt.Color(63, 25, 56));
        textContrasena.setForeground(new java.awt.Color(255, 255, 255));
        textContrasena.setMinimumSize(new java.awt.Dimension(15, 24));
        textContrasena.setPreferredSize(new java.awt.Dimension(15, 24));
        add(textContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 188, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("CONTRASEÑA");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, 20));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("FECHA DE NACIMIENTO");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, 30));

        jDateNacimiento.setBackground(new java.awt.Color(63, 25, 56));
        jDateNacimiento.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jDateNacimiento.setMaxSelectableDate(new java.util.Date(1609480877000L));
        jDateNacimiento.setMinSelectableDate(new java.util.Date(-1262281483000L));
        add(jDateNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 150, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("TIPO DE USUARIO");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, 30));

        radbtnCliente.setBackground(new java.awt.Color(38, 11, 32));
        buttonGroup1.add(radbtnCliente);
        radbtnCliente.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        radbtnCliente.setForeground(new java.awt.Color(255, 255, 255));
        radbtnCliente.setSelected(true);
        radbtnCliente.setText("CLIENTE");
        add(radbtnCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, -1, -1));

        radbtnAdmin.setBackground(new java.awt.Color(38, 11, 32));
        buttonGroup1.add(radbtnAdmin);
        radbtnAdmin.setForeground(new java.awt.Color(255, 255, 255));
        radbtnAdmin.setText("ADMIN");
        add(radbtnAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, -1, -1));

        btnCancelar.setBackground(new java.awt.Color(0, 0, 0));
        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/iconos/error.png"))); // NOI18N
        btnCancelar.setText("CANCELAR");
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, -1, 44));

        btnRegistrarse.setBackground(new java.awt.Color(34, 12, 51));
        btnRegistrarse.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRegistrarse.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/iconos/usuario (1).png"))); // NOI18N
        btnRegistrarse.setText("REGISTRARSE");
        btnRegistrarse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(btnRegistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 360, -1, 44));

        btnExaminar.setBackground(new java.awt.Color(34, 12, 51));
        btnExaminar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnExaminar.setForeground(new java.awt.Color(255, 255, 255));
        btnExaminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/iconos/mas (1).png"))); // NOI18N
        btnExaminar.setText("Examinar...");
        btnExaminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(btnExaminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, 125, -1));

        lblFoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        lblFoto.setMaximumSize(new java.awt.Dimension(100, 100));
        lblFoto.setMinimumSize(new java.awt.Dimension(100, 100));
        lblFoto.setPreferredSize(new java.awt.Dimension(100, 100));
        add(lblFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, 125, 124));

        lblpassseguro.setForeground(new java.awt.Color(255, 51, 102));
        add(lblpassseguro, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 190, 20));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/fondo-login1.png"))); // NOI18N
        jLabel8.setOpaque(true);
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 612, 428));
    }// </editor-fold>//GEN-END:initComponents

    public JLabel getLblpassseguro() {
        return lblpassseguro;
    }

    public void setLblpassseguro(JLabel lblpassseguro) {
        this.lblpassseguro = lblpassseguro;
    }

    public JButton getBtnCancelar() {
        return btnCancelar;
    }

    public void setBtnCancelar(JButton btnCancelar) {
        this.btnCancelar = btnCancelar;
    }

    public JButton getBtnExaminar() {
        return btnExaminar;
    }

    public void setBtnExaminar(JButton btnExaminar) {
        this.btnExaminar = btnExaminar;
    }

    public JButton getBtnRegistrarse() {
        return btnRegistrarse;
    }

    public void setBtnRegistrarse(JButton btnRegistrarse) {
        this.btnRegistrarse = btnRegistrarse;
    }

    public JDateChooser getjDateNacimiento() {
        return jDateNacimiento;
    }

    public void setjDateNacimiento(JDateChooser jDateNacimiento) {
        this.jDateNacimiento = jDateNacimiento;
    }

    public JLabel getLblFoto() {
        return lblFoto;
    }

    public void setLblFoto(JLabel lblFoto) {
        this.lblFoto = lblFoto;
    }

    public JRadioButton getRadbtnAdmin() {
        return radbtnAdmin;
    }

    public void setRadbtnAdmin(JRadioButton radbtnAdmin) {
        this.radbtnAdmin = radbtnAdmin;
    }

    public JRadioButton getRadbtnCliente() {
        return radbtnCliente;
    }

    public void setRadbtnCliente(JRadioButton radbtnCliente) {
        this.radbtnCliente = radbtnCliente;
    }

    public JPasswordField getTextContrasena() {
        return textContrasena;
    }

    public void setTextContrasena(JPasswordField textContrasena) {
        this.textContrasena = textContrasena;
    }

    public JTextField getTextCorreo() {
        return textCorreo;
    }

    public void setTextCorreo(JTextField textCorreo) {
        this.textCorreo = textCorreo;
    }

    public JTextField getTextNombre() {
        return textNombre;
    }

    public void setTextNombre(JTextField textNombre) {
        this.textNombre = textNombre;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExaminar;
    private javax.swing.JButton btnRegistrarse;
    private javax.swing.ButtonGroup buttonGroup1;
    private com.toedter.calendar.JDateChooser jDateNacimiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JLabel lblpassseguro;
    private javax.swing.JRadioButton radbtnAdmin;
    private javax.swing.JRadioButton radbtnCliente;
    private javax.swing.JPasswordField textContrasena;
    private javax.swing.JTextField textCorreo;
    private javax.swing.JTextField textNombre;
    // End of variables declaration//GEN-END:variables
}
